// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.639
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func index() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Document</title><script src=\"/js/htmx.min.js\"></script><style>\r\n\t\t\t\t#not-found {\r\n\t\t\t\t\topacity: 0;\r\n\t\t\t\t}\r\n\t\t\t</style></head><body><button hx-post=\"/integrations/1\">Pull Contacts from integration\r</button> <button hx-get=\"/not-found\">test 404</button><table hx-get=\"/contacts/table\" hx-trigger=\"contacts-updated from:body\"></table><div id=\"not-found\">404 \r</div></body><script>\r\n\t\t\tfunction showNotFoundError() {\r\n\t\t\t\tlet notFound = document.getElementById(\"not-found\")\t\r\n\t\t\t\tnotFound.style.opacity = 1\r\n\t\t\t}\r\n\t\t\tdocument.body.addEventListener('htmx:beforeSwap', function(evt) {\r\n\t\t\tconsole.log(evt.detail.xhr, \"xhr\")\r\n\t\t\t\tif (evt.detail.xhr.status === 404) {\r\n\t\t\t\t\tshowNotFoundError()\r\n\t\t\t\t}\r\n\t\t\t})\r\n\t\t</script></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
